### ISSUE TITLE
Question on flags

### ISSUE THREAD

**Issue by IzzySoft** [styluslabs/maps#7]
The APK at your latest release is compiled for debug, and has the `usesCleartextTraffic`. Could you please provide a release build – and either remove the `usesCleartextTraffic` or clarify why it's needed? Thanks in advance!

**Comment by pbsurf** [comment]
I assume by "compiled for debug", you mean that `android:debuggable = true`.  This is done for convenience - so I don't need to deal with multiple builds and can debug problems on my device without installing a different build.  The binary itself is a "release" build (-O2 optimization, symbols stripped).

`usesCleartextTraffic` is needed because not all tile servers support https

**Comment by IzzySoft** [comment]
Yes, I meant `android:debuggable = true` – which is not intended for distribution as it also has security implications. Which is why at the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid), we do not accept such APKs (I was looking to integrate your app there). The explanation for `usesCleartextTraffic` is totally fine, we'd just make this transparent then.

**Comment by IzzySoft** [comment]
Another point is the signing key used:

```
Number of signers: 1
Signer #1 certificate DN: O=Stylus Labs, L=Mountain View, ST=CA
Signer #1 certificate SHA-256 digest: 10c6776d7f16a4e5979721e5ef233310f5438b924643f632809f65471761a98c
Signer #1 certificate SHA-1 digest: 25a4314dd170c3815397d2d6a910c9f3f7b6fa05
Signer #1 certificate MD5 digest: 117339acbd2f8e148f368d815bfe57ca
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 1024
Signer #1 public key SHA-256 digest: e488a569cf1a0f609f67f17a4b0459f8391644d995aa3860cc8c6a15bb9e7a74
Signer #1 public key SHA-1 digest: 64bcbebf9e3d12a6e18cf30495e66085eed93cae
Signer #1 public key MD5 digest: 91477f66f3f6aad38cce70d462077c92
Signature algorithm name: SHA1withRSA (weak)
Subject Public Key Algorithm: 1024-bit RSA key (weak)
The certificate uses the SHA1withRSA signature algorithm which is considered a security risk. This algorithm will be disabled in a future update.
The certificate uses a 1024-bit RSA key which is considered a security risk. This key size will be disabled in a future update.
```

SHA1withRSA + 1024-bit RSA is double-weak combination. As the comment suggests, it's just a matter of time when this will no longer be accepted by Android itself. Convenience is one thing, but this is a security question.

`usesCleartextTraffic` is acceptable in this case, as you outlined why it's needed. But debug + weak key, that's not for distribution.  It might be OK for "local test versions", but APKs for distribution should be compiled for release and protected with a stronger key.

So no bad feelings, but for my orientation:  do you plan to change that – or should I strike Maps from my watch-list (and stop bothering you)?

**Comment by pbsurf** [comment]
Created a new release with APK using SHA384withRSA + 4096-bit key.  I'm planning to look into using Github actions or something to automate builds so adding a build with debuggable=false would be straightforward.  I can update this thread at that time.

**Comment by pbsurf** [comment]
Sorry for the delay!  The latest release has `debuggable=false` now: https://github.com/styluslabs/maps/releases/download/v1.0-rc6/ascend-700cab3.apk

**Comment by IzzySoft** [comment]
I've noticed; the original APK disappeared in the middle of a run here 🙈 

I tried to build, but obviously I miss some dependencies:

    make: /home/runner/android-sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++: No such file or directory

My build recipe (we use [rbtlog](https://codeberg.org/IzzyOnDroid/rbtlog) for [Reproducible Builds](https://reproducible-builds.org/) here, see e.g. [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)):

```yaml
---
repository: https://github.com/styluslabs/maps.git
updates: releases
notes:
  - find JDK, NDK, cmake etc. versions in app/android/gww
versions:
  - tag: v1.0-rc6
    apks:
      - apk_pattern: ascend.*\.apk
        apk_url: https://github.com/styluslabs/maps/releases/download/v1.0-rc6/ascend-android-700cab3.apk
        build:
          - sdkmanager --sdk_root=/usr/local/lib/android/sdk --install 'platform-tools'
          - sed -r '/signingConfigs.debug/d' -i app/android/app/build.gradle
          - cd app/android
          - git clone https://codeberg.org/IzzyOnDroid/gradlew.py
          - gradlew.py/gradlew.py -v assembleRelease -Papp_versioncode=$(git tag -l | wc -l) -Papp_versionname=$(git describe --tags)
          - find . -name '*.apk'
          - mv app/build/outputs/apk/release/*unsigned.apk /outputs/unsigned.apk
        build_cpus:
        build_home_dir: /home/runner
        build_repo_dir: /home/runner/work/maps/maps
        build_timeout:
        build_user: runner
        provisioning:
          android_home: /usr/local/lib/android/sdk
          build_tools: 34.0.0
          cmake: 3.18.1
          cmdline_tools:
            version: '19.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip
            sha256: 7ec965280a073311c339e571cd5de778b9975026cfcbe79f2b1cdcb1e15317ee
          extra_packages:
            - build-essential
            - curl
            - python3
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk: 26.3.11579264
          platform: android-34
          platform_tools:
          tools:
          verify_gradle_wrapper: false
```

I've matched the environment (home, build dir, etc) to what Github actions use (important with native stuff, as that often embeds build paths etc) in case you wonder. And we use our own gradle wrapper, if there's none in the repo (also to verify the gradle binaries).

Any clue what I might have missed?

**Comment by pbsurf** [comment]
Try removing the `ndk: 26.3.11579264` and make sure ANDROID_NDK is set in the environment.  I just have the fallback to 26.3.11579264 for my computer - ANDROID_NDK is already set to something on the Github actions runner.

**Comment by pbsurf** [comment]
OTOH, if the goal is to generate an identical binary to mine, you could get that NDK version from here: https://github.com/android/ndk/wiki/Unsupported-Downloads  I'll update my NDK version to something newer for the next release.

**Comment by IzzySoft** [comment]
Oops, looks like both notifications were lost… Well, guess we better wait for an official NDK then:

* removing NDK and then setting ANDROID_NDK to … what, if there is no NDK anymore then?
* yes, the goal is to generate an identical binary

Looking forward to the next release then – and to you naming the corresponding NDK version.

**Comment by IzzySoft** [comment]
> Is the rbtlog build machine ARM or something other than linux x86-64?

All our current builders are amd64 (not sure about the independent builders, though).

> what is the first missing directory in that path?

Can't tell "from outside" – all builds run in ephemeral containers, which are abandoned at build end. If no NDK is installed, all from `ndk` on might be missing. With ndk:26.3.11579264 installed, at least `26.3.11579264` should be there.

OK, so I've added a bunch of `ls` commands to the build recipe to find out (oh my, half a gigabyte downloads just for that) – and it's the toolchains which are already missing:

```
+ ls -l /home/runner/android-sdk/ndk/26.3.11579264/toolchains
ls: cannot access '/home/runner/android-sdk/ndk/26.3.11579264/toolchains': No such file or directory
```

Is there an `sdkmanager` command to install them?

**Comment by IzzySoft** [comment]
```
+ sdkmanager --sdk_root=/usr/local/lib/android/sdk --verbose --install 'ndk;26.3.11579264'
Info: Parsing /usr/local/lib/android/sdk/build-tools/34.0.0/package.xml         
Info: Parsing /usr/local/lib/android/sdk/cmake/3.18.1/package.xml
Info: Parsing legacy package: /usr/local/lib/android/sdk/cmdline-tools/19.0
Info: Parsing /usr/local/lib/android/sdk/platforms/android-34/package.xml
Info: Preparing "Install NDK (Side by side) 26.3.11579264 v.26.3.11579264".     
Info: "Install NDK (Side by side) 26.3.11579264 v.26.3.11579264" ready.         
Info: Installing NDK (Side by side) 26.3.11579264 in /usr/local/lib/android/sdk/ndk/26.3.11579264
[=======================================] 100% Unzipping... android-ndk-r26d/sha
Info: "Install NDK (Side by side) 26.3.11579264 v.26.3.11579264" complete.
Info: "Install NDK (Side by side) 26.3.11579264 v.26.3.11579264" finished.

+ sdkmanager --sdk_root=/usr/local/lib/android/sdk --install platform-tools
[=======================================] 100% Unzipping... platform-tools/sqlit

+ ls -l /home/runner/android-sdk/ndk/26.3.11579264/toolchains
ls: cannot access '/home/runner/android-sdk/ndk/26.3.11579264/toolchains': No such file or directory
```

And getting a

```
+ ls -l /home/runner/android-sdk/ndk/26.3.11579264
ls: cannot access '/home/runner/android-sdk/ndk/26.3.11579264': No such file or directory
```

gave me the final hint: Github actions has the SDK installed in `/usr/local/lib/android/sdk` (which is why I've set it to that, assuming you'd build with Github actions), so that's also where the NDK and the toolchains will be – but you seem to install it into `/home/runner/android-sdk`… Why a custom location? Not that we could not adjust to it, was just causing a little confusion 🙈 So, that found, we're getting somewhere:

```
+ ls -l /home/runner/android-sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin
total 705752
```

Builds now, but is not reproducible:

```diff
- -rw-r--r--  0.0 unx  1143496 b-   487882 defN 1981-01-01 01:01:02 ed88a707 classes.dex
- -rw-r--r--  0.0 unx  5715112 b-  2507791 defN 1981-01-01 01:01:02 28d8ca15 lib/arm64-v8a/libdroidmaps.so
+ Archive:  ./647798ba15b314a94d248a85c19487879c0d31e4cb08d5835802916546a3112e-com.styluslabs.maps-v1.0-rc6-unsigned.apk
+ Zip file size: 5728190 bytes, number of entries: 76
+ -rw-r--r--  0.0 unx       56 b-       52 defN 1981-01-01 01:01:02 1290bb28 META-INF/com/android/build/gradle/app-metadata.properties
+ -rw-r--r--  0.0 unx       46 b-       48 defN 1981-01-01 01:01:02 b8ff6554 META-INF/version-control-info.textproto
+ -rw-r--r--  0.0 unx  1143316 b-   487887 defN 1981-01-01 01:01:02 6544721c classes.dex
+ -rw-r--r--  0.0 unx  5720088 b-  2510032 defN 1981-01-01 01:01:02 b73818cf lib/arm64-v8a/libdroidmaps.so
  -rw-r--r--  0.0 unx     2829 b-     1460 defN 1981-01-01 01:01:02 5f673159 assets/config.default.yaml
  -rw-r--r--  0.0 unx    12992 b-     4343 defN 1981-01-01 01:01:02 c4674c3f assets/mapsources.default.yaml
  -rw-r--r--  0.0 unx      660 b-      367 defN 1981-01-01 01:01:02 6a853080 assets/plugins/brouter.js
@@ -39,8 +41,11 @@
  -rw-r--r--  0.0 unx   218408 b-    76546 defN 1981-01-01 01:01:02 19820f09 assets/shared/fonts/SanFranciscoDisplay-Regular.otf
  -rw-r--r--  0.0 unx     3107 b-     1369 defN 1981-01-01 01:01:02 71e2a327 assets/shared/icons/app-icon.svg
  -rw-r--r--  0.0 unx     4439 b-     4439 stor 1981-01-01 01:01:02 78e4202e assets/shared/icons/app144x144.png
+ -rw----     2.4 fat        6 b-        6 stor 1981-01-01 01:01:02 ddfd6504 META-INF/androidx.core_core.version
+ -rw----     2.4 fat        6 b-        6 stor 1981-01-01 01:01:02 7beadac6 META-INF/androidx.lifecycle_lifecycle-runtime.version
+ -rw----     2.4 fat        6 b-        6 stor 1981-01-01 01:01:02 45c2cf0d META-INF/androidx.versionedparcelable_versionedparcelable.version
  -rw----     2.4 fat    34000 b-    34000 stor 1981-01-01 01:01:02 5fccc77e okhttp3/internal/publicsuffix/publicsuffixes.gz
- -rw----     0.0 fat     5916 b-     1743 defN 1981-01-01 01:01:02 8c6bc6af AndroidManifest.xml
+ -rw----     0.0 fat     5916 b-     1743 defN 1981-01-01 01:01:02 4d9f04f0 AndroidManifest.xml
  -rw----     0.0 fat      225 b-      225 stor 1981-01-01 01:01:02 5059e725 res/2K.9.png
  -rw----     0.0 fat      138 b-      138 stor 1981-01-01 01:01:02 04576501 res/5c.png
  -rw----     0.0 fat      304 b-      173 defN 1981-01-01 01:01:02 86247a41 res/9m.xml
@@ -70,8 +75,5 @@
  -rw----     0.0 fat     2456 b-      785 defN 1981-01-01 01:01:02 f42355bb res/xN.xml
  -rw----     0.0 fat      221 b-      221 stor 1981-01-01 01:01:02 3ad03275 res/xa.9.png
  -rw----     0.0 fat      221 b-      221 stor 1981-01-01 01:01:02 9944f31a res/z-.9.png
- -rw----     0.0 fat    20244 b-    20244 stor 1981-01-01 01:01:02 bc7c587c resources.arsc
+ -rw----     0.0 fat    19848 b-    19848 stor 1981-01-01 01:01:02 8d534834 resources.arsc
```

First observation: your build lacks the `META-INF/version-control-info.textproto` – so you have built outside the git tree, which makes it hard to find why RB fails – as we have no indicator what commit you've built from; and you definitely did NOT built from the tagged commit, because:

Second observation: `AndroidManifest.xml` differs. Let's see:

```diff
     XML ELEM START [lineno=2, name='manifest', #attributes=7]
-      ATTR: http://schemas.android.com/apk/res/android:versionCode=11
+      ATTR: http://schemas.android.com/apk/res/android:versionCode=8
       ATTR: http://schemas.android.com/apk/res/android:versionName='v1.0-rc6'
```

Quite a jump, from 8 to 11 (and considering we both used `-Papp_versioncode=`git tag -l` this is very strange: your build was done in some quite different location, seemingly a git tree having 3 additional tags, and with a config that disabled `vcsInfo`?). So IMHO it does not make sense to dive into the other differences before we find common ground here.

Where to go now, or how to approach it? Would you consider building from (a clean tree at) the tagged commit, inside the git tree as it is here at Github (i.e. without additional tags), so we have a common base?

**Comment by pbsurf** [comment]
I could switch to using the APK generated by the Github workflow for releases (just resigning it manually on my computer) if that would make things easier.  I updated the android job to upload the APK artifact: https://github.com/styluslabs/maps/actions/runs/20799083815 (uses the default NDK for the Github runner, looks like 27.3.13750724) - is that closer to your build?

**Comment by pbsurf** [comment]
I think this is due to the `ANDROID_NDK` env var not being defined.  I updated to using `ANDROID_NDK_HOME` which seems more common (both are defined on the Github runner): https://github.com/styluslabs/maps/actions/runs/21096057473

**Comment by pbsurf** [comment]
I assumed the rbtlog runner was similar to a github runner, which defines a number of env vars, including `ANDROID_HOME` and `ANDROID_NDK_HOME`.  Is there some way I can test and debug the build myself on a rbtlog runner?

**Comment by IzzySoft** [comment]
Oh – yes, `ANDROID_HOME` is set automatically – but `ANDROID_NDK_HOME` is not. And yes, our tooling is fully FOSS, so you can use it yourself. We've prepared [rbuilder_setup](https://codeberg.org/IzzyOnDroid/rbuilder_setup) for that, so you can have a fully working setup ready in less than 5 minutes: just edit the configs to your liking, then run the script. Works on multiple Linux distributions (preferably use a Debian based, that's best tested). I can attach you the recipes for your app I've used so far, if you want them as starters.

**Comment by pbsurf** [comment]
Here's what I did:
1. ran rbuilder_setup
2. Created ~/builder/rbtlog/recipes/com.styluslabs.maps.yml:
```
---
repository: https://github.com/styluslabs/maps.git
updates: releases
notes:
  - find JDK, NDK, cmake etc. versions in app/android/gww
versions:
  - tag: v1.0-rc6
    apks:
      - apk_pattern: ascend.*\.apk
        apk_url: https://github.com/styluslabs/maps/releases/download/v1.0-rc6/ascend-android-700cab3.apk
        build:
          - sdkmanager --sdk_root=/usr/local/lib/android/sdk --install 'platform-tools'
          - sed -r '/signingConfigs.debug/d' -i app/android/app/build.gradle
          - cd app/android
          - git clone https://codeberg.org/IzzyOnDroid/gradlew.py
          - gradlew.py/gradlew.py -v assembleRelease -Papp_versioncode=$(git tag -l | wc -l) -Papp_versionname=$(git describe --tags)
          - find . -name '*.apk'
          - mv app/build/outputs/apk/release/*unsigned.apk /outputs/unsigned.apk
        build_cpus:
        build_home_dir: /home/runner
        build_repo_dir: /home/runner/work/maps/maps
        build_timeout:
        build_user: runner
        provisioning:
          android_home: /usr/local/lib/android/sdk
          build_tools: 34.0.0
          cmake: 3.18.1
          cmdline_tools:
            version: '19.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip
            sha256: 7ec965280a073311c339e571cd5de778b9975026cfcbe79f2b1cdcb1e15317ee
          extra_packages:
            - build-essential
            - curl
            - python3
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk: 27.3.13750724
          platform: android-34
          platform_tools:
          tools:
          verify_gradle_wrapper: false
```

4. Ran: `python3 scripts/build.py --local --keep-apks ${HOME}/builder/rbtlog/apk -v podman com.styluslabs.maps:v1.0-rc6:7bc2f88: |tee z.log`  (commit https://github.com/styluslabs/maps/commit/7bc2f881e578156b152db3dea2f62486a503abe4 )
5. The build completed and the attached APK was created in ~/builder/rbtlog/apk (changed extension to .zip so github would let me attach):

[6c65d8eafc5f41d8ddbb7974f3e6f1dd59a9dcfe9546ff70cbac83c8ce77ea24-com.styluslabs.maps-7bc2f88-unsigned.zip](https://github.com/user-attachments/files/25319000/6c65d8eafc5f41d8ddbb7974f3e6f1dd59a9dcfe9546ff70cbac83c8ce77ea24-com.styluslabs.maps-7bc2f88-unsigned.zip)

The APK is not identical to the one from github actions workflow ( https://github.com/styluslabs/maps/actions/runs/21802691025 ) - unsigned vs. debug signed is one obvious reason.  The github runner also has multiple versions of Android build tools, and I don't know which ones it is using.  I can add some logging to print these during the github actions build.
